config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
    TokenBlacklistView
)

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('registration/',include('registration.urls',namespace='registration.registration')),
    path('movies/',include('movies.urls',namespace='movies.movies')),
    path('actors/',include('actors.urls',namespace='actors.actors')),
    path('articles/', include('articles.urls', namespace ='articles.articles')),
    path('contacts/',include('contacts.urls',namespace='contacts.contacts')),
    #JWT URLs START
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
    #JWT URLS END
    #CAPTCHA
    path('captcha/', include('captcha.urls')),
    
    path('', include('pages.urls', namespace='pages.pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import (
    ShowMoviePageDetailView,
    MovieActorsListView,
    ShowLatestMoviesListView,
    ShowUpcomingMoviesListView,
    ShowMonthTopMoviesListView,
    UserRateMovieDetailView,
    UserDeleteRateMovieDetailView,
    UserLikeUnlikeMovie,
)
app_name = 'movies'
urlpatterns = [
    path('detail/<int:pk>', ShowMoviePageDetailView.as_view(), name='movie_detail'),
    path('<int:pk>/actors', MovieActorsListView.as_view(), name='movie_actors'),
    path('<int:pk>/rate', UserRateMovieDetailView.as_view(), name='user_movie_rate'),
    path('<int:pk>/rate/delete', UserDeleteRateMovieDetailView.as_view(), name='user_movie_rate_delete'),
    path('<int:pk>/<str:action>', UserLikeUnlikeMovie.as_view(), name='user_movie_like_unlike'),
    path('latest', ShowLatestMoviesListView.as_view(), name='latest_movies'),    
    path('upcoming', ShowUpcomingMoviesListView.as_view(), name='upcoming_movies'),
    path('month-top', ShowMonthTopMoviesListView.as_view(), name='month_top_movies'),  

]

pages/urls.py
from django.urls import path
from .views import (
    MainpageTemplateView,
    FilteredMoviesListView,
    filter_movies,
    ProfileTemplateView,
    search_movies,
    SearchResultsListView,
    UserArticlesListView,
    UserFavoriteMoviesListView,
    UserFavoriteMoviesAddDetailView,
    UserFavoriteMoviesRemoveDetailView,
    ModeratorCommentsListView,
)
from articles.views import CommmentDeleteView
app_name = 'pages'
urlpatterns = [
    path('filter/movies/', filter_movies, name='filter_movies'),
    path('filtered/<int:option>/movies/',FilteredMoviesListView.as_view(), name='filtered_movies'),
    path('profile/', ProfileTemplateView.as_view(), name='profile_page'),
    path('search/', search_movies, name='search_movies'),
    path('search/<str:query>', SearchResultsListView.as_view(), name='search_results'),
    path('my/articles/', UserArticlesListView.as_view(), name='user_articles'),
    path('my/favorites/', UserFavoriteMoviesListView.as_view(), name='user_favorites'),
    path('my/favorites/<int:pk>/add/', UserFavoriteMoviesAddDetailView.as_view(), name='user_favorites_add'),
    path('my/favorites/<int:pk>/remove/', UserFavoriteMoviesRemoveDetailView.as_view(), name='user_favorites_remove'),
    # path('moderator/comments', ModeratorCommentsListView.as_view(), name='moderator_comments'),
    # path('moderator/comments/<uuid:comment_id>/delete', CommmentDeleteView.as_view(), name='comment_delete'),
    path('', MainpageTemplateView.as_view(), name='mainpage'),
]           

registration/urls.py
from django.urls import path
from .views import (
    RegisterAPIView,
    RegisterView,
    LoginView,
    LogoutView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    EmailConfirmTemplateView,
    NewPasswordTemplateView
)

app_name = 'registration'
urlpatterns = [
    path('api/register/', RegisterAPIView.as_view(), name='register_api'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password/change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('email/confirm/', EmailConfirmTemplateView.as_view(), name='email_confirm'),
    path('password/new/', NewPasswordTemplateView.as_view(), name='new_password'),
]

templates/pages/favorite_movies.html
{% extends 'layout/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    


        <!-- =============== START OF PAGE HEADER =============== -->
        <section class="page-header overlay-gradient" style="background: url(assets/images/posters/movie-collection.jpg);">
            <div class="container">
                <div class="inner">
                    <h2 class="title">Favorite Movies</h2>
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li>Favorite Movies</li>
                    </ol>
                </div>
            </div>
        </section>
        <!-- =============== END OF PAGE HEADER =============== -->



        <!-- =============== START OF MAIN =============== -->
        <main class="ptb100">
            <div class="container">

                {% if object_list %}
                <!-- Start of Movie List -->
                <div class="row">
                    {% for movie in page_obj %}
                    <!-- Watch Later Item -->
                    <div class="col-md-12 col-sm-12">
                        <div class="watch-later-item">
                            <div class="listing-container">

                                <!-- Movie List Image -->
                                <div class="listing-image">
                                    {% if movie.image %}
                                        <img src="{{ movie.image.url }}"class="img-shadow" alt="">
                                    {% else %}
                                        <img src="{% static 'assets/images/posters/no_image.jpg' %}" class="img-shadow" alt="">
                                    {% endif %}
                                </div>

                                <!-- Movie List Content -->
                                <div class="listing-content">
                                    <div class="inner">
                                        <h3 class="title"><a href="{% url 'movies:movie_detail' movie.pk %}" >{{ movie.title }}</a></h3>
                                        {% if movie.overview %}
                                        <p>{{ movie.overview|get_two_sentences }}</p>
                                        {% else %}
                                        <p>There is not description</p>
                                        {% endif %}

                                        <a href="{% url 'pages:user_favorites_remove' movie.pk %}" class="btn btn-main btn-effect">Delete From Favorites</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- End of Movie List -->



                <!-- Start of Pagination -->
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <nav class="pagination">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a href="?page=1"><i class="ti-angle-double-left"></i></a></li>
                                    <li><a href="?page={{ page_obj.previous_page_number }}"><i class="ti-angle-left"></i></a></li>
                                {% endif %}

                                <li><a href="?page=page_obj.number"  class="current-page">{{page_obj.number}}</a></li>
                                {% if page_obj.has_next %}  
                                    <li><a href="?page={{ page_obj.next_page_number }}" >{{ page_obj.next_page_number }}</a></li>
                                {% endif %}
                                    
                                
                                
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}"><i class="ti-angle-right"></i></a></li>
                                    <li><a href="?page={{ paginator.num_pages }}"><i class="ti-angle-double-right"></i></a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- End of Pagination -->

                {% else %}
                    <h2>You Don't Have Favorites Yet</h2>
                    <a href="{% url 'pages:mainpage' %}" class="btn btn-main btn-effect">Search For Movies</a>
                {% endif %}

            </div>
        </main>
        <!-- =============== END OF MAIN =============== -->



        {% endblock content %}
    

templates/pages/profile.html
{% extends 'layout/base.html' %}
{% load static %}


{% block content %}
{% include 'messages/messages.html' %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            
            {% if user.user_profile.avatar %}
                <img class="rounded-circle mt-5" width="150px"src="{{ user.user_profile.avatar.url }}">
            {% else %}
                <img class="rounded-circle mt-5" width="150px"src="{% static 'assets/images/user.png' %}">
            {% endif %}
                
            
            {% if user.user_profile.username %}
                <span class="font-weight-bold">{{ user.user_profile.username }}</span>
            {% endif %}
                
            
            <span class="text-black-50">{{ user.email }}</span>
            <span> </span>
            <a class="btn btn-main btn-effect" href="{% url 'registration:password_change' %}">Change Password</a>
            
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div> 
                <form method='POST' enctype="multipart/form-data" > 
                    {% csrf_token %}
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Email</label>{{ user_form.email }}</div>
                    <div class="col-md-12"><label class="labels"> Username </label>  {{ user_profile_form.username }}</div>
                    <div class="col-md-12"><label class="labels"> Phone Number</label>  {{ user_profile_form.phone_number }}</div>
                    <div class="col-md-12"><label class="labels">Birth Date</label>  {{ user_profile_form.birth_date }}</div>
                    <div class="col-md-12"><label class="labels">Avatar</label>  {{ user_profile_form.avatar }}</div>
        
                </div>
          
                <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="sumit">Save Profile</button></div>
            </div>
        </form>
        </div>
    </div>
</div>
{% endblock content %}
    