actors/urls.py
from django.urls import path
from .views import(
    ShowActorPageDetailView,
   
)
app_name = 'actors'

urlpatterns = [
    path('detail/<int:pk>', ShowActorPageDetailView.as_view(), name = 'actor_detail'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
    TokenBlacklistView
)

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('registration/',include('registration.urls',namespace='registration.registration')),
    path('movies/',include('movies.urls',namespace='movies.movies')),
    path('actors/',include('actors.urls',namespace='actors.actors')),
    path('articles/', include('articles.urls', namespace ='articles.articles')),
    path('contacts/',include('contacts.urls',namespace='contacts.contacts')),
    #JWT URLs START
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
    #JWT URLS END
    #CAPTCHA
    path('captcha/', include('captcha.urls')),
    
    path('', include('pages.urls', namespace='pages.pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import (
    ShowMoviePageDetailView,
    MovieActorsListView,
    ShowLatestMoviesListView,
    ShowUpcomingMoviesListView,
    ShowMonthTopMoviesListView,
    UserRateMovieDetailView,
    UserDeleteRateMovieDetailView,
    UserLikeUnlikeMovie,
)
app_name = 'movies'
urlpatterns = [
    path('detail/<int:pk>', ShowMoviePageDetailView.as_view(), name='movie_detail'),
    path('<int:pk>/actors', MovieActorsListView.as_view(), name='movie_actors'),
    path('<int:pk>/rate', UserRateMovieDetailView.as_view(), name='user_movie_rate'),
    path('<int:pk>/rate/delete', UserDeleteRateMovieDetailView.as_view(), name='user_movie_rate_delete'),
    path('<int:pk>/<str:action>', UserLikeUnlikeMovie.as_view(), name='user_movie_like_unlike'),
    path('latest', ShowLatestMoviesListView.as_view(), name='latest_movies'),    
    path('upcoming', ShowUpcomingMoviesListView.as_view(), name='upcoming_movies'),
    path('month-top', ShowMonthTopMoviesListView.as_view(), name='month_top_movies'),  

]

pages/urls.py
from django.urls import path
from .views import (
    MainpageTemplateView,
    FilteredMoviesListView,
    filter_movies,
    ProfileTemplateView,
    search_movies,
    SearchResultsListView,
    UserArticlesListView,
    UserFavoriteMoviesListView,
    UserFavoriteMoviesAddDetailView,
    UserFavoriteMoviesRemoveDetailView,
    ModeratorCommentsListView,
)
from articles.views import CommmentDeleteView
app_name = 'pages'
urlpatterns = [
    path('filter/movies/', filter_movies, name='filter_movies'),
    path('filtered/<int:option>/movies/',FilteredMoviesListView.as_view(), name='filtered_movies'),
    path('profile/', ProfileTemplateView.as_view(), name='profile_page'),
    path('search/', search_movies, name='search_movies'),
    path('search/<str:query>', SearchResultsListView.as_view(), name='search_results'),
    path('my/articles/', UserArticlesListView.as_view(), name='user_articles'),
    path('my/favorites/', UserFavoriteMoviesListView.as_view(), name='user_favorites'),
    path('my/favorites/<int:pk>/add/', UserFavoriteMoviesAddDetailView.as_view(), name='user_favorites_add'),
    path('my/favorites/<int:pk>/remove/', UserFavoriteMoviesRemoveDetailView.as_view(), name='user_favorites_remove'),
    # path('moderator/comments', ModeratorCommentsListView.as_view(), name='moderator_comments'),
    # path('moderator/comments/<uuid:comment_id>/delete', CommmentDeleteView.as_view(), name='comment_delete'),
    path('', MainpageTemplateView.as_view(), name='mainpage'),
]           

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Movie
from actors.models import Actor
from django.views.generic import (
    DetailView,
    ListView,

)
from django.contrib import messages
from datetime import date, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from icecream import ic
from django.db import transaction
from django.http import Http404
# Create your views here.


def mins_convert_hours(mins):
    """
    Конвертирует минуты в формат "часы минуты".

    Параметры:
        - mins (int): Количество минут.

    Возвращает:
        - str (str): Строковое представление времени в формате "часы минуты".
    """
    if mins < 60:
        return f'{mins}min'
    else:
        hours = mins // 60
        mins = mins % 60
        return f'{hours}h {mins}min'


class ShowMoviePageDetailView(DetailView):
    """
    Класс для отображения страницы детальной информации о фильме.

    Атрибуты:
        context_object_name (str): Имя переменной для объекта фильма в шаблоне.
        model (django.db.models.Model): Класс модели, представляющий фильма.
        template_name (str): Имя шаблона, используемого для отображения страницы с подробной информацией о фильме.
    """
    context_object_name = 'movie'
    model = Movie
    template_name = 'movies/movie_detail.html'

    def get_title(self, movie_instance):
        """
        Возвращает заголовок фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - str (str): Заголовок фильма.
            - None: Если заголовок слишком длинный.
        """
        if len((movie_instance.title)) <= 36:
            return movie_instance.title
        else:
            return None

    def get_runtime(self, movie_instance):
        """
        Возвращает продолжительность фильма в формате "часы минуты".

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - str (str): Продолжительность фильма в формате "часы минуты".
            - 'Unknown Runtime' (str): Если продолжительность неизвестна.
        """
        runtime = movie_instance.runtime
        if runtime:
            return mins_convert_hours(runtime)
        else:
            return 'Unknown Runtime'

    def get_orig_lang(self, movie_instance):
        """
        Возвращает оригинальный язык фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - str (str): Оригинальный язык фильма.
            - 'Unknown' (str): Если язык неизвестен.
        """
        original_language = movie_instance.original_language
        if original_language:
            return original_language
        else:
            return 'Unknown'

    def get_budjet(self, movie_instance):
        """
        Возвращает бюджет фильма в формате "бюджет USD".

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - str (str): Бюджет фильма в формате "сумма USD".
            - 'Unknown' (str): Если бюджет неизвестен.
        """
        budjet = movie_instance.budjet
        if budjet:
            return f'{budjet} USD'
        else:
            return 'Unknown'

    def get_overview(self, movie_instance):
        """
        Возвращает описание фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - str (str): Описание фильма.
            - 'No Description for current movie' (str): Если описание отсутствует.
        """
        overview = movie_instance.overview
        if overview:
            return overview
        else:
            return 'No Description for current movie'

    def get_popularity(self, movie_instance):
        """
        Возвращает популярность фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - float (float): Популярность фильма.
            - 'Unknown' (str): Если популярность неизвестна.
        """
        popularity = movie_instance.popularity
        if popularity:
            return popularity
        else:
            return 'Unknown'

    def get_vote_average(self, movie_instance):
        """
        Возвращает среднюю оценку фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - float (float): Средняя оценка фильма.
            - 'Unknown' (str): Если оценка неизвестна.
        """
        vote_average = movie_instance.vote_average
        if vote_average:
            return vote_average
        else:
            return 'Unknown'

    def get_vote_count(self, movie_instance):
        """
        Возвращает количество голосов для фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - int (int): Количество голосов для фильма.
            - None: Если количество голосов неизвестно.
        """
        vote_count = movie_instance.vote_count
        if vote_count:
            return vote_count
        else:
            return None

    def get_image(self, movie_instance):
        """
        Возвращает изображение фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - ImageField (ImageField): Изображение фильма.
            - None: Если изображение отсутствует.
        """
        image = movie_instance.image
        if image:
            if 'None' in image.url:
                return None
            else:
                return image
        else:
            return None

    def get_genres(self, movie_instance):
        """
        Возвращает жанры фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - QuerySet (QuerySet): QuerySet жанров фильма.
            - None: Если жанры неизвестны.
        """
        genres = movie_instance.genres
        if genres:
            return genres.all()
        else:
            return None

    def get_actors(self, movie_instance):
        """
        Возвращает актеров фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - QuerySet (QuerySet): QuerySet актеров фильма (максимум 4 актера).
            - None: Если актеры неизвестны.
        """
        actors = movie_instance.actors
        if actors:
            return actors.all()[:4]
        else:
            return None

    def get_release_date(self, movie_instance):
        """
        Возвращает дату релиза фильма.

        Параметры:
            - movie_instance (Movie): Объект фильма.

        Возвращает:
            - date (date): Дата релиза фильма.
            - None: Если дата релиза неизвестна.
        """
        release_date = movie_instance.release_date
        if release_date:
            return release_date
        else:
            return None

    def user_rate(self, request):
        """
        Проверяет, оценил ли пользователь фильм.

        Параметры:
            - request: Запрос пользователя.
        Возвращает:
            - rating (int/float): Оценка пользователя для фильма.
            - False: Если пользователь не аутентифицирован.
        """
        if request.user.is_authenticated:
            movie = self.get_object()
            user_profile = request.user.user_profile
            movie_ratings = user_profile.movie_ratings
            rating = movie_ratings.get(str(movie.tmbd_id))
            if rating:
                return rating
            return False
        return False
    
    def user_like(self, request):
        if request.user.is_authenticated:
            movie = self.get_object()
            user_profile = request.user.user_profile
            liked_movies = user_profile.liked_movies.all()
            if movie in liked_movies:
                return True
            return False
        return False

    def get_context_data(self, **kwargs):
        """
        Получает данные контекста страницы детальной информации о фильме.

        Параметры:
            - **kwargs: Дополнительные аргументы.

        Возвращает:
            - context (dict): Словарь данных контекста.
        """
        context = super(ShowMoviePageDetailView,
                        self).get_context_data(**kwargs)
        movie_instance = self.get_object()
        context['full_title'] = movie_instance.title
        context['title'] = self.get_title(movie_instance=movie_instance)

        context['runtime'] = self.get_runtime(movie_instance=movie_instance)
        context['original_language'] = self.get_orig_lang(
            movie_instance=movie_instance)
        context['budjet'] = self.get_budjet(movie_instance=movie_instance)
        context['overview'] = self.get_overview(movie_instance=movie_instance)
        context['popularity'] = self.get_popularity(
            movie_instance=movie_instance)
        context['vote_average'] = self.get_vote_average(
            movie_instance=movie_instance)
        context['vote_count'] = self.get_vote_count(
            movie_instance=movie_instance)
        context['image'] = self.get_image(movie_instance=movie_instance)
        context['genres'] = self.get_genres(movie_instance=movie_instance)
        context['actors'] = self.get_actors(movie_instance=movie_instance)
        context['release_date'] = self.get_release_date(
            movie_instance=movie_instance)
        context['user_rate'] = self.user_rate(request=self.request)
        context['user_like'] = self.user_like(request=self.request)
        return context

    def get(self, request, *args, **kwargs):
        """
    Обрабатывает GET-запрос на страницу.
    Добавляет в сессию предыдущий url 

    Параметры:
        - request: Запрос пользователя.
        - *args: Дополнительные позиционные аргументы.
        - **kwargs: Дополнительные именованные аргументы.

    Возвращает:

templates/movies/movie_actors.html
{% extends 'layout/base.html' %}
{% load static %}
{% load custom_tags %}


{% block content %}
    
<section class="page-header overlay-gradient" style="background: url(assets/images/posters/movie-collection.jpg);">
    <div class="container">
        <div class="inner">
            
            <h2 class="title">Actors of movie : {{ current_movie.title }} </h2>
          
            <h4 class="title"><a href = "{% url 'movies:movie_detail' current_movie.pk %}"> Return to Movie</a></h4>
        </div>
    </div>
</section>
    
        <!-- =============== START OF MAIN =============== -->
        <main class="ptb100">
            <div class="container">
            
                {% if object_list %}
                    
                
                    
                <!-- Start of Celebrities Grid -->
                <div class="row">
                    {% for actor in page_obj  %}
                        
                    
                        
                    <!-- Celebrity Grid Item -->
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="celebrity-grid-1">
                            <div class="celeb-container">

                                <!-- Celebrity Image -->
                                <div class="celebrity-image">
                                    <a href="{% url 'actors:actor_detail' actor.pk %}">
                                        {% if actor.image %}
                                            <img src="{{ actor.image.url }}" alt="">
                                        {% else %}
                                            <img src="{% static 'assets/images/user.png' %}" alt="">
                                        {% endif %}
                                    </a>
                                </div>

                                <!-- Celebrity Content -->
                                <div class="celebrity-content">
                                    <div class="inner">
                                        <h3 class="title"><a href="{% url 'actors:actor_detail' actor.pk %}">{{ actor.name }}</a></h3>
                                       
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- Celebrity Grid Item -->
                    

                </div>
                <!-- End of Celebrities Grid -->



                <!-- Start of Pagination -->
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <nav class="pagination">
                            <ul>
                                
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}"><i class="ti-angle-left"></i></a></li>
                                {% endif %}

                                <li><a href="?page=1" {% if page_obj.number == 1 %} class="current-page" {% endif %}>1</a></li>
                                {% if paginator.num_pages > 1 %}
                                    <li><a href="?page=2" {% if page_obj.number == 2 %} class="current-page" {% endif %}>2</a></li>
                                    {% if paginator.num_pages > 2 %}
                                        <li><a href="?page=3" {% if page_obj.number == 3 %} class="current-page" {% endif %}>3</a></li>
                                    {% endif %}
                                {% endif %}
                                    
                                
                                
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}"><i class="ti-angle-right"></i></a></li>
                                {% endif %}
                                
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- End of Pagination -->
                {% else %}
                <h1>No actors for Movie: {{ current_movie.title }} </h1>
                {% endif %}

            </div>  
        </main>
        <!-- =============== END OF MAIN =============== -->

        

{% endblock content %}

templates/movies/movie_detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
{% include 'messages/messages.html' %}
<section class="movie-detail-intro overlay-gradient ptb100" style="background: url(assets/images/other/movie-detail-bg.jpg);">
</section>
<!-- =============== END OF MOVIE DETAIL INTRO =============== -->



<!-- =============== START OF MOVIE DETAIL INTRO 2 =============== -->

<section class="movie-detail-intro2">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="movie-poster">
                    
                    {% if image %}
                        <img src="{{ image.url }}" alt="">
                    {% else %}
                        <img src="{% static 'assets/images/posters/no_image.jpg' %}" alt="">
                    {% endif %}
                        
                    

                   
                </div>


                <div class="movie-details">
                    
                    {% if title %}
                        <h3 class='title'>{{ title }}</h3>
                    {% endif %}

                    <ul class="movie-subtext">  
                        <li>{{ runtime }}</li>
                    
    
                        {% if genres %}
                            <li>{% for genre in genres %} {{genre.name}}. {% endfor %}</li>
                        {% else %}
                            <li>Unknown genres</li>
                        {% endif %}
                        
                        
                        {% if release_date %}
                            <li>{{ release_date|date:"j F Y" }}</li>
                        {% else %}
                            <li>Unknown Release Date</li>
                        {% endif %}
                         
                        
                    </ul>

                    {% if movie in user.user_profile.favorite_movies.all %}
                        <a href="{% url 'pages:user_favorites_remove' movie.pk %}" class="btn btn-main btn-effect ">Remove From Favorites</a>
                    {% else %}
                        <a href="{% url 'pages:user_favorites_add' movie.pk %}" class="btn btn-main btn-effect ">Add To Favorites</a>
                    {% endif %}
                    {% if user_like %}
                        <a href="{% url 'movies:user_movie_like_unlike' pk=movie.pk action='unlike' %}" class="like-button liked">Liked {{movie.likes_count }}</a>
                    {% else %}
                        <a href="{% url 'movies:user_movie_like_unlike' pk=movie.pk action='like' %}" class="like-button unliked">Like</a>
                    {% endif %}
                    <div class="rating mt10">
                        
                    {% if vote_count > 0 %}
                        {% if movie.vote_average <= 2  %}
                            
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            
                        {% endif %}
                        {% if movie.vote_average > 2  %}
                            
                            {% if movie.vote_average <= 4 %}
                                
                               
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                               
                            {% endif %}
                        {% endif %}
                        {% if movie.vote_average > 4  %}
                            
                            {% if movie.vote_average <= 6 %}
                                
                                
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                               
                            {% endif %}
                        {% endif %}
                        {% if movie.vote_average > 6  %}
                            
                            {% if movie.vote_average <= 8 %}
                                
                                
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o"></i>
                                
                            {% endif %}
                        {% endif %}
                        {% if movie.vote_average > 8  %}
                            
                            {% if movie.vote_average <= 10 %}
                                
                                
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                            
                            {% endif %}
                        {% endif %}
                        <span>{{ vote_count }} Ratings</span>
                    {% else %}
                        <span>No Rating</span>
                    {% endif %}
                            
                        
                    </div>
                    {% if user_rate %}
                        <span>Your Rate is {{ user_rate }}</span>
                        <a href="{% url 'movies:user_movie_rate_delete' movie.pk %}" class="btn btn-main btn-effect" >Delete My Rate</a>
                    {% else %}
                        <form method="POST" action="{% url 'movies:user_movie_rate' movie.pk %}"> 
                            {% csrf_token %}
                            <div class="form-outline" style="width: 150px">
                                
                                <input name='rate_value' min="1" max="10" type="number" id="typeNumber" class="form-control">
                                
                                <button class="btn btn-main btn-effect" type="submit">Rate</button>
                                
                            </div>
                        </form>
                    {% endif %}
                      
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</section>
<!-- =============== End OF MOVIE DETAIL INTRO 2 =============== -->


<!-- =============== START OF MOVIE DETAIL MAIN SECTION =============== -->
<section class="movie-detail-main ptb100">
    <div class="container">

        <div class="row">
            <!-- Start of Movie Main -->
            <div class="col-lg-8 col-sm-12">
                <div class="inner pr50">

                    <!-- Storyline -->
                    <div class="storyline">
                        
                        <h3> {{ full_title }}</h3>
                        <h3 class="title">Storyline</h3>

                        <p>{{ overview }}</p>
                    </div>

                    <!-- Media -->
                    

                </div>
            </div>
            <!-- End of Movie Main -->


            <!-- Start of Sidebar -->
            <div class="col-lg-4 col-sm-12">
                <div class="sidebar">

                    <!-- Start of Details Widget -->
                    <aside class="widget widget-movie-details">
                        <h3 class="title">Details</h3>

                        <ul>
                            
                            {% if release_date %}
                                <li><strong>Release date: </strong>{{ release_date|date:"j F Y" }}</li>
                            {% else %}
                                <li><strong>No Release Date</strong></li>
                            {% endif %}
                                
                
                            <li><strong>Budget: </strong>{{ budjet }}</li>
                            <li><strong>Popularity: </strong>{{ popularity }}</li>
                            <li><strong>Original Language: </strong>{{ original_language }}</li>
                            <li><strong>Average Vote Rating: </strong>{{ vote_average|floatformat:2 }}</li>
                            
                        </ul>
                    </aside>
                    <!-- End of Details Widget -->

                    <!-- Start of Details Widget -->
                    <aside class="widget widget-movie-cast">
                        <h3 class="title">Cast</h3>
                        
                        {% if actors %}
                        <ul class="cast-wrapper">
                            
                            {% for actor in actors %}
                                
                            
                                
                                <li>
                                    <a href="{% url 'actors:actor_detail' actor.pk %}">
                                        <span class="circle-img">
                                            
                                            {% if actor.image %}
                                                <img src="{{ actor.image.url }}" alt="">
                                            {% else %}
                                                <img src="{% static 'assets/images/user.png' %}" alt="">
                                            {% endif %}
                                                
                                            
                                        </span>
                                        <h6 class="name">{{ actor.name }}</h6>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>

                        <a href="{% url 'movies:movie_actors' movie.pk %}" class="btn btn-main btn-effect mt20">view all</a>
                        {% else %}
                        <h3>No Cast</h3>
                        {% endif %}
                            
                        
                    </aside>
                    <!-- End of Details Widget -->

                </div>
            </div>
            <!-- End of Sidebar -->
        </div>

    </div>
</section>
<!-- =============== END OF MOVIE DETAIL MAIN SECTION =============== -->
{% endblock content %}
    