articles/urls.py
from django.urls import path
from .views import(
     ShowArticlesListView,
     ShowArticleDetailView,
     ArticleDeleteView,
     ArticleUpdateView,
     ArticleCreateView,
     ArticleCommentDeleteView,
     ArticleAddChildCommentCreateView,
)
app_name = 'articles'
urlpatterns = [
    path('create',ArticleCreateView.as_view(), name='article_create'),
    path('<slug:slug>',ShowArticleDetailView.as_view(), name='article_detail'),
    path('<slug:slug>/delete',ArticleDeleteView.as_view(), name='article_delete'),
    path('<slug:slug>/update',ArticleUpdateView.as_view(), name='article_update'),
    path('<slug:slug>/comments/<uuid:comment_id>/add',ArticleAddChildCommentCreateView.as_view(), name='article_comment_child_add'),
    path('<slug:slug>/comments/<uuid:comment_id>/delete',ArticleCommentDeleteView.as_view(), name='article_comment_delete'),
    path('',ShowArticlesListView.as_view(), name='articles_list'),


    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
    TokenBlacklistView
)

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('registration/',include('registration.urls',namespace='registration.registration')),
    path('movies/',include('movies.urls',namespace='movies.movies')),
    path('actors/',include('actors.urls',namespace='actors.actors')),
    path('articles/', include('articles.urls', namespace ='articles.articles')),
    path('contacts/',include('contacts.urls',namespace='contacts.contacts')),
    #JWT URLs START
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
    #JWT URLS END
    #CAPTCHA
    path('captcha/', include('captcha.urls')),
    
    path('', include('pages.urls', namespace='pages.pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import (
    MainpageTemplateView,
    FilteredMoviesListView,
    filter_movies,
    ProfileTemplateView,
    search_movies,
    SearchResultsListView,
    UserArticlesListView,
    UserFavoriteMoviesListView,
    UserFavoriteMoviesAddDetailView,
    UserFavoriteMoviesRemoveDetailView,
    ModeratorCommentsListView,
)
from articles.views import CommmentDeleteView
app_name = 'pages'
urlpatterns = [
    path('filter/movies/', filter_movies, name='filter_movies'),
    path('filtered/<int:option>/movies/',FilteredMoviesListView.as_view(), name='filtered_movies'),
    path('profile/', ProfileTemplateView.as_view(), name='profile_page'),
    path('search/', search_movies, name='search_movies'),
    path('search/<str:query>', SearchResultsListView.as_view(), name='search_results'),
    path('my/articles/', UserArticlesListView.as_view(), name='user_articles'),
    path('my/favorites/', UserFavoriteMoviesListView.as_view(), name='user_favorites'),
    path('my/favorites/<int:pk>/add/', UserFavoriteMoviesAddDetailView.as_view(), name='user_favorites_add'),
    path('my/favorites/<int:pk>/remove/', UserFavoriteMoviesRemoveDetailView.as_view(), name='user_favorites_remove'),
    # path('moderator/comments', ModeratorCommentsListView.as_view(), name='moderator_comments'),
    # path('moderator/comments/<uuid:comment_id>/delete', CommmentDeleteView.as_view(), name='comment_delete'),
    path('', MainpageTemplateView.as_view(), name='mainpage'),
]           

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    """
    Форма для создания и редактирования статьи.

    Атрибуты:
        title (str): Поле для ввода заголовка статьи.
        image (file): Поле для загрузки изображения к статье.

    Вложенный класс Meta:
        model (Article): Модель, с которой связана форма.
        fields (list): Список полей модели, отображаемых в форме.
        widgets (dict): Словарь виджетов для настройки отображения полей формы.

    """
    title = forms.CharField(required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Title',
                                                          'style': 'max-width: 400px;', }))
    image = forms.ImageField(required=False,
                             widget=forms.FileInput(attrs={'class': 'form-control-file'
                                                           }))

    class Meta:
        model = Article
        fields = ['title', 'content', 'image']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': "form-control",
                'style': 'max-width: 600px; resize:none',
                'placeholder': 'Your content',
                'rows': 20,
                'cols': 50,

            }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': "form-control",
                'style': 'resize:none;',
                'placeholder': 'Comment',
                'rows': 5,
                'cols': 5,

            }),
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView
)

from django.contrib.auth.mixins import (
    UserPassesTestMixin,
    LoginRequiredMixin
)
from .models import Article, Comment
from .forms import (
    ArticleForm,
    CommentForm
)
from icecream import ic
from guardian.shortcuts import get_objects_for_user
from guardian.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.core.exceptions import PermissionDenied
# Create your views here.


class ShowArticlesListView(ListView):
    """
    Контроллер класса  для отображения списка статей.

    Атрибуты класса:
        template_name (str): Имя шаблона для отображения.
        paginate_by (int): Количество статей на странице.

    Методы:
        get_queryset(): Возвращает список статей
        get_user_articles(user): Возвращает статьи, доступные пользователю для редактирования и удаления
        get_context_data(**kwargs): Метод чтобы добавить  данные контекста для отображения шаблона.

    """
    template_name = 'articles/articles_list.html'
    paginate_by = 3

    def get_queryset(self):
        """
        Возвращает список статей которые одобрены, сортировка идет по времени обновления

        Возвращаемое значение:
            QuerySet: Список статей

        """
        qs = Article.objects.filter(approved=True).order_by('-updated_at')
        return qs

    def get_user_articles(self, user):
        """
        Возвращает статьи, доступные пользователю для редактирования и удаления

        Возвращаемое значение:
            QuerySet: Список статей

        """
        user_articles = get_objects_for_user(user, 'articles.change_article')
        return user_articles

    def get_context_data(self, **kwargs):
        """
        Переопределяет базовый метод, чтобы добавить дополнительные данные контекста для отображения шаблона.


        Аргументы:
            **kwargs: Дополнительные аргументы.

        Возвращает:
            dict: Словарь с данными контекста.
        """
        context = super().get_context_data(**kwargs)
        context['latest_articles'] = self.get_queryset()[:3]
        context['user_articles'] = self.get_user_articles(
            user=self.request.user)
        return context


class ShowArticleDetailView(DetailView):
    """
    Контроллер класса  для отображения одной статьи

    Атрибуты класса:
        template_name (str): Имя шаблона для отображения.
        context_object_name (str): Имя переменной для объекта статьи в шаблоне.
        model (django.db.models.Model): Класс модели, представляющий статью.

    Методы:
        is_user_author_article(): Возвращает идентификатор есть ли у пользователся право изменять
        эту стаью
        get_user_articles(user): Возвращает статьи, доступные пользователю для редактирования и удаления
        get_context_data(**kwargs): Метод чтобы добавить  данные контекста для отображения шаблона.
        get() : Базовый метод который работает при get запросе
        post() : Базовый метод который работает при post запросе

    """
    template_name = 'articles/article_detail.html'
    context_object_name = 'article'
    model = Article

    def is_user_author_article(self, user):
        """
        Проверяет, является ли пользователь автором статьи.

        Args:
            user (User): Пользователь, для которого проверяется авторство.

        Возвращает:
            bool: True, если пользователь является автором статьи. Иначе False.
        """
        return user.has_perm('articles.change_article', self.get_object())
    def get_comments_wthout_parent_comment(self):
        comments = Comment.objects.filter(
            article=self.get_object()).order_by('-created_at').select_related('article','author')
        without_parent_comments = []
        for comment in comments:
            if not comment.parent_comment:
                without_parent_comments.append(comment)
        return without_parent_comments
    def get_context_data(self, **kwargs):
        """
        Получает контекст данных для отображения шаблона.

        Args:
            **kwargs: Дополнительные аргументы.

        Returns:
            dict: Контекст данных для шаблона.
        """
        context = super().get_context_data(**kwargs)
        context['comments'] = self.get_comments_wthout_parent_comment()
        context['latest_articles'] = Article.objects.filter(
            approved=True).order_by('-updated_at')[:3]
        context['is_user_author_article'] = self.is_user_author_article(
            user=self.request.user)
        return context

    def get(self, request, *args, **kwargs):
        """
        Обрабатывает GET-запрос.
        Если статья одобрена то будет статься показана
        В противном случае:
            Если юзер это автор стаьи то будет статья показана
            Если нет, то бдует возбуждена PermissionDenied

        Args:
            request (HttpRequest): Объект запроса.
            *args: Дополнительные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponse: Ответ на запрос.

        Raises:
            PermissionDenied: Вызывается, если пользователь не имеет доступа к статье.
        """
        movie = self.get_object()
        user = self.request.user
        if movie.approved:
            return super().get(request, *args, **kwargs)
        if self.is_user_author_article(user=user):
            return super().get(request, *args, **kwargs)
        raise PermissionDenied

    def post(self, request, *args, **kwargs):
        """
        Обрабатывает POST-запрос. Создание комментария
        Проверяет аутентификацию юзера чтобы создать комент, в противном случае
        он переотправляется залогиниться

        Args:
            request (HttpRequest): Объект запроса.
            *args: Дополнительные аргументы.
            **kwargs: Дополнительные аргументы.

        Возвращает:
            Если юзер залогинин то вызывается get()
            В противном случае перенаправляется в страницу логина
        """
        if request.user.is_authenticated:
            new_comment = Comment.objects.create(
                text=request.POST.get("comment"),
                author=request.user,
                article=self.get_object(),
            )
            new_comment.save()
            return self.get(request, *args, **kwargs)
        else:
            next_url = reverse('registration:login') + '?next=' + reverse(
                'articles:article_detail', kwargs={'slug': self.get_object().slug})

            return redirect(next_url)


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    """
    Контроллер класса  для удаления статьи

    Атрибуты класса:
        template_name (str): Имя шаблона для отображения.
        context_object_name (str): Имя переменной для объекта статьи в шаблоне.
        model (django.db.models.Model): Класс модели, представляющий статью.
        permission_required(Permission): Разрешение для отображения данного вью
        raise_exception(bool): Если True возбуждает 403 ошибку, в противном случае отправляет на страницу логина
    Методы:
        form_valid(form): Функция вызывается если форма правильно заполнена

    """
    context_object_name = 'article'
    template_name = 'articles/article_delete.html'
    model = Article
    permission_required = 'articles.delete_article' 
    raise_exception = True

    success_url = reverse_lazy('pages:user_articles')

    def form_valid(self, form):
        """
        Выполняет действия после успешного удаления статьи.

        Args:
            form (Form): Форма.

        Returns:
            HttpResponse: ответ от родительского класса
        """
        messages.success(self.request, "The Article was deleted successfully.")
        return super().form_valid(form)


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    """
    Контроллер класса  для обновления статьи

    Атрибуты класса:
        template_name (str): Имя шаблона для отображения.
        context_object_name (str): Имя переменной для объекта статьи в шаблоне.
        model (django.db.models.Model): Класс модели, представляющий статью.
        permission_required(Permission): Разрешение для отображения данного вью
        raise_exception(bool): Если True возбуждает 403 ошибку, в противном случае отправляет на страницу логина
    Методы:
        get_context_data(kwargs): Метод чтобы добавить  данные контекста для отображения шаблона.
        form_valid(form) : Функция вызывается если форма правильно заполнена
    """
    template_name = 'articles/article_form.html'
    model = Article
    permission_required = 'articles.change_article'
    raise_exception = True
    form_class = ArticleForm

    def get_context_data(self, **kwargs):
        """
        Получает контекст данных для отображения шаблона.
        action(str) - действие которое происходит
        artilce(Article)- экземпляр модели Article
        Args:
            **kwargs: Дополнительные аргументы.

        Returns:
            dict: Контекст данных для шаблона.
        """
        context = super().get_context_data(**kwargs)
        context['action'] = 'update'
        context['article'] = self.get_object()
        return context

    def form_valid(self, form):
        """
        Выполняет действия после успешного обновления статьи.

        Args:
            form (Form): Форма.

        Returns:
            HttpResponse: ответ от родительского класса
        """
        messages.success(self.request, 'Article was updated successfully')
        return super().form_valid(form)


class ArticleCreateView(UserPassesTestMixin, CreateView):
    """
    Контроллер класса  для создания статьи

    Атрибуты класса:
        template_name (str): Имя шаблона для отображения.

templates/pages/articles/user_articles.html
{% extends 'layout/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
{% include 'messages/messages.html' %}
      <!-- =============== START OF PAGE HEADER =============== -->
      <section class="page-header overlay-gradient" style="background: url(assets/images/posters/movie-collection.jpg);">
        <div class="container">
            <div class="inner">
                <h2 class="title">My Articles</h2>
                <ol class="breadcrumb">
                    <li><a href="{% url 'pages:mainpage' %}">Home</a></li>
                    <li>My Articles</li>
                </ol>
                <a href="{% url 'articles:article_create' %}" class="btn btn-icon btn-main btn-effect">
                    Add Article
                    
                </a>
            </div>
        </div>
    </section>
    <!-- =============== END OF PAGE HEADER =============== -->



    <!-- =============== START OF MAIN =============== -->
    <main class="blog-page ptb100">
        <div class="container">

            <div class="row">
                {% if object_list %}
                        
                    
                <!-- Start of Blog Posts -->
                <div class="col-lg-9 col-md-8 col-sm-12">
                    
                    
                        
                    {% for article in page_obj %}
                        
                    
                        
                    <!-- Start of Blog Post 1 -->
                    <article class="blog-post">

                        <!-- Image -->
                        <div class="blog-thumb">
                            <a href="{{ article.get_absolute_url }}" class="post-img">
                                
                                {% if article.image %}
                                    <img src="{{ article.image.url }}" alt="">
                                {% else %}
                                    <img src="{% static 'assets/images/posters/no_image.jpg' %}" alt="">
                                {% endif %}
                                    
                                
                            </a>
                        </div>

                        <!-- Content -->
                        <div class="post-content">
                            <h3 class="title">
                                <a href="{{ article.get_absolute_url }}">
                                    {{ article.title }}
                                </a>
                            </h3>

                            <ul class="post-meta">
                                <li>{{ article.updated_at|date:"F j, Y" }}</li>
                                
                                {% if article.author.user_profile.username %}
                                    <li>Author: {{ article.author.user_profile.username }}</li>
                                {% else %}
                                    <li>Unknown Author</li>
                                {% endif %}
                                    
                                
                                {% if article.get_number_comments %}
                                    <li><a href="{{ article.get_absolute_url }}">{{  article.get_number_comments }} Comments</a></li>
                                {% else %}
                                    <li>No Comments</li>
                                {% endif %}
                                    
                                
                            </ul>

                            <p>{{ article.content|get_two_sentences }}</p>

                            <a href="{{ article.get_absolute_url }}" class="read-more">
                                Read More </i>
                            </a>
                           
                            <br>    
                            <a href="{% url 'articles:article_update' article.slug %}" class="btn btn-icon btn-main btn-effect">
                                Update 
                         
                            </a>
                            <a href="{% url 'articles:article_delete' article.slug %}" class="btn btn-icon btn-main btn-effect">
                                Delete

                            </a>
                           
                        </div>

                    </article>
                    <!-- End of Blog Post 1 -->
                    {% endfor %}
              
    


                    <!-- Start of Pagination -->
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <nav class="pagination">
                                <ul>
                                    {% if page_obj.has_previous %}
                                        <li><a href="?page=1"><i class="ti-angle-double-left"></i></a></li>
                                        <li><a href="?page={{ page_obj.previous_page_number }}"><i class="ti-angle-left"></i></a></li>
                                    {% endif %}
    
                                    <li><a href="?page=page_obj.number"  class="current-page">{{page_obj.number}}</a></li>
                                    {% if page_obj.has_next %}  
                                        <li><a href="?page={{ page_obj.next_page_number }}" >{{ page_obj.next_page_number }}</a></li>
                                    {% endif %}
                                        
                                    
                                    
                                    {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}"><i class="ti-angle-right"></i></a></li>
                                        <li><a href="?page={{ paginator.num_pages }}"><i class="ti-angle-double-right"></i></a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!-- End of Pagination -->

                </div>
                {% else %}
                <h2>  There are no articles</h2>
                {% endif %}
                <!-- End of Blog Posts -->



               
            </div>

        </div>
    </main>
    <!-- =============== END OF MAIN =============== -->

{% endblock content %}
    